name = "UI Navigation"
license = "MIT"
licenselink = "https://github.com/harrymkt/hguinav/LICENSE"
description = "A theme designed for accessibility rather than visual."

# The home page of the theme, where the source can be found
homepage = "https://github.com/harrymkt/hguinav"

# If you have a running demo of the theme
demosite = "https://harrymkt.github.io/hguinav"

# Taxonomy terms
tags = ["blog", "company", "multilingual", "accessible", "accessibility", "blind"]
features = ["Multilingual", "Documentation", "Variables", "Local Date Display", "More"]

[author]
name = "Harry Min Khant"
homepage = "https://harrymkt.github.io"