name = "UI Navigation"
license = "MIT"
licenselink = "https://github.com/harrymkt/hguinav/blob/main/LICENSE.md"
description = "A modern multilingual theme designed for accessibility rather than visual."
homepage = "https://github.com/harrymkt/hguinav"
demosite = "https://harrymkt.github.io/hguinav"
tags = ["blog", "documentation", "multilingual", "accessible", "blind", "responsive", "SEO"]
features = ["Multilingual", "Documentation", "Variables", "Custom Sorting", "Local Date Display", "More"]
[author]
	name = "Harry Min Khant"
	homepage = "https://harrymkt.github.io"
