name: Release
on:
  push:
    tags: "*"
  workflow_dispatch:
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          body_path: "newest-unreleased-changes.md"
          draft: false